function m = I3D_methods( I , varargin )

  %%methods
  m = { 'at'            ...
        'weights'       ...
        'gradient'      ...
        'reduceimage'   ...
        'resample'      ...
        'spatialScale'  ...
        'center'        ...
        'transform'     ...
        'voxelvolume'   ...
        'cast'          ...
        'vec'           ...
        'bbox'          ...
        'fill'          ...
        'rot90'         ...
        'nonans'        ...
        'cleanout'      ...
        'container'     ...
        'makefull'      ...
        'dereference'   ...
        'range'         ...
        'setLABELS'     ...
        'cast'          ...
        'isfloat'       ...
        'islogical'     ...
        'tofloat'       ...
        'todouble'      ...
        'tosingle'      ...
        'toint8'        ...
        'touint8'       ...
        'toint16'       ...
        'touint16'      ...
        'toint32'       ...
        'touint32'      ...
        'tological'     ...
        'coords2matrix' 'matrix2coords' ...
        'toGPU' 'toHOST' ...
      };

end
